apiVersion: v1
kind: Service
metadata:
  name: kurento
  labels:
    app: kurento
spec:
  type: ClusterIP
  selector:
    app: kurento
  ports:
  - port: 8888
    name: kurento
    targetPort: kurento
