apiVersion: apps/v1
kind: Deployment
metadata:
  name: signaling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: signaling
  template:
    metadata:
      labels:
        app: signaling
    spec:
      containers:
      - name: signaling
        image: k8saksacr.azurecr.io/tech-sketch/kurento-signaling:0.0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: signaling
        env:
        - name: PORT
          value: "3000"
        - name: KURENTO_URL
          value: "ws://kurento-0.kurento:8888/kurento"
        - name: APPSERVER_URL
          value: "http://signaling:3000/"
        - name: OVERLAY_IMG_PATH
          value: "static/img/mario-wings.png"
        - name: STUN_LIST
          valueFrom:
            secretKeyRef:
              name: signaling-turnserver
              key: STUN_LIST
        - name: TURN_LIST
          valueFrom:
            secretKeyRef:
              name: signaling-turnserver
              key: TURN_LIST
